#!/bin/bash
echo "--- Starten met downloaden van modellen ---"

# Zorg dat de mappen bestaan
mkdir -p /workspace/runpod-slim/ComfyUI/models/checkpoints
mkdir -p /workspace/runpod-slim/ComfyUI/models/clip
mkdir -p /workspace/runpod-slim/ComfyUI/models/diffusion_models
mkdir -p /workspace/runpod-slim/ComfyUI/models/LLM
mkdir -p /workspace/runpod-slim/ComfyUI/models/loras
mkdir -p /workspace/runpod-slim/ComfyUI/models/upscale_models
mkdir -p /workspace/runpod-slim/ComfyUI/models/vae

# Download Checkpoints
echo "Download t5_umt5-xxl-enc-bf16..."
wget -c "https://huggingface.co/Wan-AI/Wan2.2-Animate-14B/blob/main/models_t5_umt5-xxl-enc-bf16.pth"  -O "/workspace/runpod-slim/ComfyUI/models/clip/models_t5_umt5-xxl-enc-bf16.pth"

# Download VAE
echo "Download WAN2.1 VAE..."
wget -c "https://huggingface.co/Wan-AI/Wan2.2-Animate-14B/blob/main/Wan2.1_VAE.pth" -O "/workspace/runpod-slim/ComfyUI/models/vae/Wan2.1_VAE.pth"

echo "--- Alle downloads voltooid ---"
