#!/bin/bash
echo "--- Starten met downloaden van modellen ---"

# Zorg dat de mappen bestaan
mkdir -p /workspace/runpod-slim/ComfyUI/models/checkpoints
mkdir -p /workspace/runpod-slim/ComfyUI/models/clip
mkdir -p /workspace/runpod-slim/ComfyUI/models/diffusion_models
mkdir -p /workspace/runpod-slim/ComfyUI/models/LLM
mkdir -p /workspace/runpod-slim/ComfyUI/models/loras
mkdir -p /workspace/runpod-slim/ComfyUI/models/upscale_models
mkdir -p /workspace/runpod-slim/ComfyUI/models/vae

# Checkpoints
wget -nc -c "https://huggingface.co/stabilityai/stable-diffusion-3.5-large/resolve/main/sd3.5_large.safetensors" -O "/workspace/runpod-slim/ComfyUI/models/checkpoints/sd3.5_large.safetensors"

# Loras
wget -nc -c "https://huggingface.co/Comfy-Org/Wan_2.2_ComfyUI_Repackaged/resolve/main/split_files/loras/wan2.2_animate_14B_relight_lora_bf16.safetensors" -O "/workspace/runpod-slim/ComfyUI/models/loras/wan2.2_animate_14B_relight_lora_bf16.safetensors
wget -nc -c "https://huggingface.co/Comfy-Org/Wan_2.2_ComfyUI_Repackaged/resolve/main/split_files/loras/wan2.2_i2v_lightx2v_4steps_lora_v1_high_noise.safetensors" -O "/workspace/runpod-slim/ComfyUI/models/loras/wan2.2_i2v_lightx2v_4steps_lora_v1_high_noise.safetensors
wget -nc -c "https://huggingface.co/Comfy-Org/Wan_2.2_ComfyUI_Repackaged/resolve/main/split_files/loras/wan2.2_i2v_lightx2v_4steps_lora_v1_low_noise.safetensors" -O "/workspace/runpod-slim/ComfyUI/models/loras/wan2.2_i2v_lightx2v_4steps_lora_v1_low_noise.safetensors

# Text Encoders
wget -nc -c "https://huggingface.co/Comfy-Org/Wan_2.2_ComfyUI_Repackaged/resolve/main/split_files/text_encoders/umt5_xxl_fp8_e4m3fn_scaled.safetensors" -O "/workspace/runpod-slim/ComfyUI/models/text_encoders/umt5_xxl_fp8_e4m3fn_scaled.safetensors"
# OF wget -nc -c "https://huggingface.co/Comfy-Org/Wan_2.2_ComfyUI_Repackaged/resolve/main/split_files/text_encoders/umt5_xxl_fp16.safetensors" -O "/workspace/runpod-slim/ComfyUI/models/text_encoders/umt5_xxl_fp16.safetensors"

# VAE
echo "Download WAN VAEs..."
wget -nc -c "https://huggingface.co/Comfy-Org/Wan_2.2_ComfyUI_Repackaged/resolve/main/split_files/vae/wan_2.1_vae.safetensors" -O "/workspace/runpod-slim/ComfyUI/models/vae/wan2.1_vae.safetensors"
wget -nc -c "https://huggingface.co/Comfy-Org/Wan_2.2_ComfyUI_Repackaged/resolve/main/split_files/vae/wan2.2_vae.safetensors" -O "/workspace/runpod-slim/ComfyUI/models/vae/wan2.2_vae.safetensors"

echo "--- Alle downloads voltooid ---"
